### PR TITLE
change static DB credentials to flexible

### PR DESCRIPTION
**Pull request by fxagung**
Hi Thomas,

Kindly review this changes. Thank you.

Regards,
Agung

### CODE REVIEW

**Review by mitrais-cdc-cpp — CHANGES_REQUESTED** [review]
test

**Comment by fxagung** [comment]
Hi Thomas,

I've refactored the code as per your review. Kindly review it again. 
here is the link to the changes:https://github.com/mitrais-cdc-cpp/Nemsta/commit/7b89037c12a61e07e3eac73b3dcf50a09a851063

Thank you

Regards,
Agung

**Comment by mitrais-cdc-cpp** [comment]
can be set as done

**Comment by mitrais-cdc-cpp** [comment]
deleted remote branch since feature is done

**Pull request merged**
